model:
  class_path: torchdrum.tasks.TorchDrumParameterMapping
  init_args:
    model: models/mlp_mapper.yaml
    synth: synths/simple_drum_synth.yaml
    feature: features/onset_feature_full.yaml
    loss_fn: torchdrum.loss.FeatureDifferenceLoss
    preset: cfg/presets/drum_1.json
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.00005
lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    monitor: train/loss
    factor: 0.5
    patience: 150
    verbose: true
data: data/snare_onset.yaml
trainer:
  devices: [0]
  accelerator: gpu
  max_epochs: 500
  callbacks:
    - class_path: torchdrum.callback.SaveAudioCallback
    - class_path: torchdrum.callback.SaveTorchScriptCallback
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
