model:
  class_path: torchdrum.tasks.TorchDrumParameterMapping
  init_args:
    model: models/mlp_mapper.yaml
    synth: synths/simple_drum_synth.yaml
    feature: features/feature_interval.yaml
    loss_fn: torchdrum.loss.FeatureDifferenceLoss
    preset: cfg/presets/drum_1.json
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.000005
# lr_scheduler:
#   class_path: lightning.pytorch.cli.ReduceLROnPlateau
#   init_args:
#     monitor: val/loss
#     factor: 0.5
#     patience: 100
#     verbose: true
data: data/snare_1.yaml
trainer:
  devices: [0]
  accelerator: gpu
  val_check_interval: 100
  max_epochs: 1
  callbacks:
    - class_path: torchdrum.callback.SaveAudioCallback
    - class_path: torchdrum.callback.SaveTorchScriptCallback
